// Mock API service
export const generatePresentation = async (prompt, provider = 'openrouter') => {
  console.log(`Generating presentation with prompt: "${prompt}" using ${provider}`);
  
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  return {
    id: `pres-${Date.now()}`,
    title: prompt.length > 30 ? prompt.substring(0, 30) + '...' : prompt,
    slides: [
      {
        id: 's1',
        type: 'title',
        content: { title: prompt, subtitle: 'Generated by DeckForge AI' },
        theme: { backgroundColor: '#ffffff', textColor: '#1a1a1a', accentColor: '#3b82f6' }
      },
      {
        id: 's2',
        type: 'content',
        content: { title: 'Overview', body: '• Point 1\n• Point 2\n• Point 3' },
        theme: { backgroundColor: '#ffffff', textColor: '#1a1a1a', accentColor: '#3b82f6' }
      },
      {
        id: 's3',
        type: 'closing',
        content: { title: 'Thank You!', subtitle: 'Generated in seconds' },
        theme: { backgroundColor: '#ffffff', textColor: '#1a1a1a', accentColor: '#3b82f6' }
      }
    ]
  };
};

export const exportPresentation = async (presentation, format = 'pdf') => {
  console.log(`Exporting presentation to ${format}`);
  await new Promise(resolve => setTimeout(resolve, 1500));
  return { url: '#' };
};
