from pptx import Presentation as PptxPresentation
from pptx.util import Inches, Pt
import io
from app.services.llm import Presentation as PresentationModel

class PPTXService:
    def create_presentation(self, data: PresentationModel) -> io.BytesIO:
        prs = PptxPresentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = data.title
        subtitle.text = "Generated by DeckForge"
        
        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        
        for slide_data in data.slides:
            slide = prs.slides.add_slide(bullet_slide_layout)
            title_shape = slide.shapes.title
            title_shape.text = slide_data.title
            
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            
            for point in slide_data.content:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
                
            if slide_data.speaker_notes:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = slide_data.speaker_notes
                
        pptx_io = io.BytesIO()
        prs.save(pptx_io)
        pptx_io.seek(0)
        return pptx_io
