import io
import logging

from pptx import Presentation as PptxPresentation
from pptx.util import Inches, Pt  # noqa: F401
from app.services.llm import Presentation as PresentationModel

logger = logging.getLogger(__name__)


class PPTXService:
    def create_presentation(self, data: PresentationModel) -> io.BytesIO:
        prs = PptxPresentation()
        
        try:
            title_slide_layout = prs.slide_layouts[0]
        except IndexError:
            raise ValueError("Default presentation template has no title slide layout")

        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        if title is None:
            raise ValueError("Title slide layout is missing a title placeholder")
        title.text = data.title

        try:
            subtitle = slide.placeholders[1]
            subtitle.text = "Generated by DeckForge"
        except KeyError:
            logger.warning("Title slide layout has no subtitle placeholder; skipping subtitle")
        
        try:
            bullet_slide_layout = prs.slide_layouts[1]
        except IndexError:
            raise ValueError("Default presentation template has no content slide layout")
        
        for idx, slide_data in enumerate(data.slides):
            slide = prs.slides.add_slide(bullet_slide_layout)

            title_shape = slide.shapes.title
            if title_shape is None:
                logger.warning("Slide %d: layout has no title placeholder", idx)
            else:
                title_shape.text = slide_data.title

            try:
                body_shape = slide.placeholders[1]
            except KeyError:
                logger.warning("Slide %d (%s): layout has no body placeholder; skipping content", idx, slide_data.title)
                continue

            tf = body_shape.text_frame
            for point in slide_data.content:
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
                
            if slide_data.speaker_notes:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = slide_data.speaker_notes
                
        pptx_io = io.BytesIO()
        prs.save(pptx_io)
        pptx_io.seek(0)
        return pptx_io
